---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: web
  namespace: solve
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: mutex-app
    namespace: common
  values:
    service:
      ports:
        - &api_port 4242
        - &ui_port 8080

    solve_image: &solve_image udovin/solve:master
    ui_image: &ui_image udovin/solve-web:master

    replicaCount: 2

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000

    deployment:
      enabled: true
      initContainers:
        solve-migrate:
          image: udovin/solve:master
          command: [ "solve" ]
          args: [ "migrate" ]
          configMapPath: /etc/solve
          env: &solve_env
            - name: SOLVE_CONFIG
              value: /etc/solve/server-config.json
            - name: DB_NAME
              value: solve
          envFrom: &solve_envFrom
            - secretRef: 
                name: solve-secret
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp/solve-safeexec
      containers:
        frontend:
          image: *ui_image
          ports:
            - containerPort: *ui_port
          configMapPath: /etc/solve
          readinessProbe:
            tcpSocket:
              port: *ui_port
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        api:
          image: *solve_image
          args:
            - server
          ports:
            - containerPort: *api_port
          env: *solve_env 
          envFrom: *solve_envFrom 
          configMapPath: /etc/solve
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp/solve-safeexec
          readinessProbe:
            httpGet:
              path: /api/health
              port: *api_port
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

    volumes:
      - name: tmpfs
        emptyDir:
          medium: Memory

    persistence:
      enabled: false

    configMap:
      enabled: true
      server-config.json: |
        {
          "db": {
            "driver": "postgres",
            "options": {
              "hosts": [
                "main-db-cluster-rw.cnpg-database.svc.cluster.local:5432"
              ],
              "user": {{ "{{" }} env "DB_USER" | json {{ "}}" }},
              "password": {{ "{{" }} env "DB_PASSWORD" | json {{ "}}" }},
              "name": {{ "{{" }} env "DB_NAME" | json {{ "}}" }}
            }
          },
          "server": {
            "port": 4242,
            "site_url": "https://solve.bsuir.by"
          },
          "security": {
            "password_salt": {{ "{{" }} env "PASSWORD_SALT" | json {{ "}}" }}
          },
          "storage": {
            "driver": "s3",
            "options": {
              "region": "ru-central1",
              "access_key_id": {{ "{{" }} env "ACCESS_KEY_ID" | json {{ "}}" }},
              "secret_access_key": {{ "{{" }} env "SECRET_ACCESS_KEY" | json {{ "}}" }},
              "endpoint": "https://storage.yandexcloud.net",
              "bucket": "solve-bsuir",
              "path_prefix": "testing/files/"
            }
          },
          "socket_file": "/tmp/solve-server.sock",
          "smtp": {
            "host": "mail.bsuir.by",
            "port": 465,
            "email": {{ "{{" }} env "SMTP_EMAIL" | json {{ "}}" }},
            "password": {{ "{{" }} env "SMTP_PASSWORD" | json {{ "}}" }}
          },
          "log_level": "debug"
        }

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      hosts:
        - host: solve.bsuir.by
          paths:
            - path: /api/
              pathType: Prefix
              servicePort: *api_port
            - path: /
              pathType: Prefix
              servicePort: *ui_port
      tls:
        - hosts:
          - solve.bsuir.by
          secretName: bsuir-tls
