---
apiVersion: v1
kind: Namespace
metadata:
  name: solve
  labels:
    toolkit.fluxcd.io/tenant: studunion
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoker
  namespace: solve
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: mutex-app
    namespace: common
  values:
    replicaCount: 1

    service:
      enabled: false

    podSecurityContext:
      fsGroup: 1000

    deployment:
      enabled: true
      initContainers:
        solve-init-cgroup:
          image: &solve_image udovin/solve:master
          command: [ "/bin/sh" ]
          args:
            - -c
            - chown -R solve:solve "/sys/fs/cgroup$(dirname $(cat /proc/self/cgroup | cut -d ':' -f 3))"
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp/solve-safeexec
      containers:
        server:
          image: *solve_image
          command: [ "solve" ]
          args:
            - server
          configMapPath: /etc/solve
          env:
            - name: SOLVE_CONFIG
              value: /etc/solve/server-config.json
            - name: DB_NAME
              value: solve       
          envFrom:
            - secretRef: 
                name: solve-secret   
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp/solve-safeexec
          securityContext:
            privileged: true
            runAsUser: 1000
            runAsGroup: 1000

    volumes:
      - name: tmpfs
        emptyDir:
          medium: Memory

    persistence:
      enabled: false

    configMap:
      enabled: true
      invoker-config.json: |
        {
          "db": {
            "driver": "postgres",
            "options": {
              "hosts": [
                "main-db-cluster-rw.cnpg-database.svc.cluster.local:5432"
              ],
              "user": {{ "{{" }} env "DB_USER" | json {{ "}}" }},
              "password": {{ "{{" }} env "DB_PASSWORD" | json {{ "}}" }},
              "name": {{ "{{" }} env "DB_NAME" | json {{ "}}" }}
            }
          },
          "invoker": {
            "workers": 2,
            "safeexec": {
              "path": "/bin/safeexec"
            }
          },
          "security": {
            "password_salt": {{ "{{" }} env "PASSWORD_SALT" | json {{ "}}" }}
          },
          "storage": {
            "driver": "s3",
            "options": {
              "region": "ru-central1",
              "access_key_id": {{ "{{" }} env "ACCESS_KEY_ID" | json {{ "}}" }},
              "secret_access_key": {{ "{{" }} env "SECRET_ACCESS_KEY" | json {{ "}}" }},
              "endpoint": "https://storage.yandexcloud.net",
              "bucket": "solve-testing",
              "path_prefix": "testing/files/"
            }
          },
          "socket_file": "/tmp/solve-server.sock",
          "smtp": {
            "host": "smtp.yandex.ru",
            "port": 465,
            "email": {{ "{{" }} env "SMTP_EMAIL" | json {{ "}}" }},
            "password": {{ "{{" }} env "SMTP_PASSWORD" | json {{ "}}" }}
          },
          "log_level": "debug"
        }
