---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: yandex-s3
  namespace: kube-system
spec:
  interval: 24h
  url: https://yandex-cloud.github.io/k8s-csi-s3/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-s3
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-s3
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: yandex-s3
        namespace: kube-system
      interval: 12h
  values:
    storageClass:
      singleBucket: bsuir-k8s-test
