---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vm
  namespace: monitoring
spec:
  interval: 24h
  url: https://victoriametrics.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmks
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: monitoring
      interval: 12h
  values:
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    vmagent:
      enabled: true
    vmsingle:
      spec:
        retentionPeriod: 2w
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
        storage:
          storageClassName: local-path
          resources:
            requests:
              storage: 4Gi
    grafana:
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 400Mi
      grafana.ini:
        server:
          domain: olymp.bsuir.by
          root_url: "%(protocol)s://%(domain)s/i/grafana"
          serve_from_sub_path: true
        auth.github:
          enabled: true
          allow_sign_up: true
          scopes: user:email,read:org
          auth_url: https://github.com/login/oauth/authorize
          token_url: https://github.com/login/oauth/access_token
          api_url: https://api.github.com/user
          allowed_organizations: fcsan-bsuir
          client_id: Ov23lieTzgx1dPonnETx
          client_secret: ${GITHUB_OAUTH_SECRET}
          allow_assign_grafana_admin: true
          role_attribute_path: >
            contains(groups[*], '@fcsan-bsuir/devops') && 'Admin' || 
            'Viewer'
          skip_org_role_sync: false
      envValueFrom:
        GITHUB_OAUTH_SECRET:
          secretKeyRef:
            name: github-oauth
            key: client_secret
      ingress:
        enabled: true
        path: /i/grafana
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/affinity: "cookie"
        hosts:
          - olymp.bsuir.by
        tls:
          - hosts:
            - olymp.bsuir.by
            secretName: bsuir-tls

    alertmanager:
      spec:
        configSecret: vkms-alertmanager-config
      templates:
        telegram.tmpl: |-
          {{ define "alert_list" }}{{ range . }}
          🪪 <b>{{ .Labels.alertname }}</b>
          {{- if eq .Labels.severity "critical" }}
          🚨 CRITICAL {{ end }}
          {{- if eq .Labels.severity "warning" }}
          ⚠️ WARNING {{ end }}
          {{- if .Annotations.summary }}
          📝 {{ .Annotations.summary }}{{ end }}
          {{- if .Annotations.description }}
          📖 {{ .Annotations.description }}{{ end }}
          {{ end }}
          🛠 <a href="https://olymp.bsuir.by/i/grafana">Grafana</a> 💊
          {{ end }}

          {{ define "telegram.message" }}
          {{ if gt (len .Alerts.Firing) 0 }}
          🔥 Alerts Firing 🔥
          {{ template "alert_list" .Alerts.Firing }}
          {{ end }}
          {{ if gt (len .Alerts.Resolved) 0 }}
          ✅ Alerts Resolved ✅
          {{ template "alert_list" .Alerts.Resolved }}
          {{ end }}
          {{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmks-grafana-nginx
  namespace: monitoring
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_folder: NGINX
data:
  request-handling-performance.json.url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/heads/main/deploy/grafana/dashboards/request-handling-performance.json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmks-grafana-cloud-native-pg
  namespace: monitoring
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_folder: Database
data:
  cloud-native-pg.json.url: "https://raw.githubusercontent.com/cloudnative-pg/grafana-dashboards/refs/heads/main/charts/cluster/grafana-dashboard.json"
