---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: deploy-errors
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: deploy-notifications
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: info
  eventSources: # FIXME: template this
    - kind: HelmRelease
      name: '*'
      namespace: acm
    - kind: HelmRelease
      name: '*'
      namespace: solve
    - kind: HelmRelease
      name: '*'
      namespace: monitoring
    - kind: HelmRelease
      name: '*'
      namespace: mnt-placeholder
    - kind: HelmRelease
      name: '*'
      namespace: cnpg-database
