---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 12h
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  labels:
    app.kubernetes.io/instance: victoria-metrics
  name: cnpg-controller-manager
  namespace: cnpg-system
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      scrapeTimeout: 120s
      interval: 60s
      relabelConfigs:
        - target_label: job
          replacement: cloudnative-pg
  selector:
    matchLabels:
     app.kubernetes.io/name: cloudnative-pg
