---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-database
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-database
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: main-db
  namespace: cnpg-database
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-database
      interval: 12h
  values:
    cluster:
      instances: 2
      storage:
        size: 1Gi
        storageClass: local-path
      affinity:
        topologyKey: kubernetes.io/hostname
      monitoring:
        enabled: true
        prometheusRule:
          enabled: false
      postgresql:
        pg_hba:
          - host all all all md5
