---
apiVersion: v1
kind: Namespace
metadata:
  name: common
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mutex-app
  namespace: common
spec:
  interval: 5m0s
  url: oci://registry.gitlab.com/mutualex/charts/mutex-app/mutex-app
  secretRef:
    name: mutex-gitlab-cr
  ref:
    tag: "v0.12"
