---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 24h
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-runner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      interval: 12h
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
      clusterWideAccess: false
      rules:
        - resources: ["configmaps", "pods", "pods/attach", "secrets", "services"]
          verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
        - apiGroups: [""]
          resources: ["pods/exec"]
          verbs: ["create", "patch", "delete"]
    serviceAccount:
      create: true
    runners:
      secret: gitlab-runner-secret
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "alpine"
            image_pull_secrets = [ "mutex-gitlab-cr" ]
