---
apiVersion: v1
kind: Namespace
metadata:
  name: mnt-placeholder
  labels:
    toolkit.fluxcd.io/tenant: studunion
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mnt-placeholder
  namespace: mnt-placeholder
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mutex-app
    namespace: common
  values:
    service:
      ports:
        - &exposed 8080
      exposed: *exposed

    deployment:
      enabled: true
      containers:
        backend:
          image: ghcr.io/fcsan-bsuir/mnt-placeholder:v1.1.1
          # image: nginx:latest
          # configMapPath: /usr/share/nginx/html
    imagePullSecrets:
      - name: fcsan-gh-cr

    configMap:
      enabled: false
      index.html: |
        <!DOCTYPE html>
        <html lang="ru">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>&#9881;Техническое обслуживание</title>
            <style>
                body {
                    font-family: sans-serif;
                    text-align: center;
                    margin: 0;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    min-height: 100vh;
                    background-color: #f0f0f0;
                }

                .container {
                    background-color: #fff;
                    padding: 40px;
                    border-radius: 10px;
                    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
                }

                h1 {
                    font-size: 36px;
                    margin-bottom: 20px;
                    color: #333;
                }

                p {
                    font-size: 18px;
                    margin-bottom: 10px;
                    color: #666;
                }


                a {
                position: relative;
                text-decoration: none;
                color: #00583F;
                }

                a::before {
                content: "";
                position: absolute;
                bottom: -2px;
                left: 0;
                width: 0;
                height: 2px;
                background-color: #00583F;
                transition: width 0.3s ease-in-out;
                }

                a:hover::before {
                width: 100%;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Техническое обслуживание</h1>
                <p>Сайт временно недоступен. Работы будут завершены в ближайшее время.</p>
                <p>Хотите помочь нам сделать сайт еще лучше? <a href="mailto:fksis.studsovet@gmail.cim">Напишите нам!</a></p>
            </div>
        </body>
        </html>

    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: olymp.bsuir.by
          paths:
            - path: /
              pathType: ImplementationSpecific
        # - host: solve.bsuir.by
        #   paths:
        #     - path: /
        #       pathType: ImplementationSpecific
        - host: bit-cup.bsuir.by
          paths:
            - path: /
              pathType: ImplementationSpecific
        # - host: acm.bsuir.by
        #   paths:
        #     - path: /
        #       pathType: ImplementationSpecific
      tls:
        - hosts:
          - olymp.bsuir.by
          # - solve.bsuir.by
          - bit-cup.bsuir.by
          # - acm.bsuir.by
          secretName: bsuir-tls
